application: ipsumimage
version: 2-2-4
runtime: python27
threadsafe: false
api_version: 1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /style.css
  static_files: static/style.css
  upload: static/style.css
- url: /test
  static_files: static/test.html
  upload: static/test.html
- url: /about
  static_files: static/about.html
  upload: static/about.html
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: /google96f127342fdae2a8.html
  static_files: static/google96f127342fdae2a8.html
  upload: static/google96f127342fdae2a8.html
- url: .*
  script: main.py

libraries:
- name: django
  version: "1.3"
- name: PIL
  version: "1.1.7"